### ISSUE TITLE
yeastStarvationData repo gives "Not found" HTTP error

### ISSUE THREAD

**Issue by mtietjen27** [warrenmcg/sleuth-ALR#1]
Hi,

I can't seem to download the yeast example dataset as indicated in the vignette - it looks like it's not available anymore?

```> devtools::install_github('warrenmcg/yeastStarvationData')
Error: HTTP error 404.
  Not Found

  Rate limit remaining: 56/60
  Rate limit reset at: 2019-03-14 11:55:23 UTC
```

Thanks!

**Comment by warrenmcg** [comment]
Hi @mtietjen27,

Thanks for using sleuth-ALR! I apologize for the error here. It turns out I forgot to make the `yeastStarvationData` repo public, which meant that only I could see it. I have made it public, so please try again, and let me know if you come across any further issues!

Because I think I solved the problem, I'm going to close this issue, but please re-open if you continue to have trouble installing the yeastStarvationData package.

**Comment by mtietjen27** [comment]
Hi @warrenmcg,
it's working now. Thank you for the quick response and solution!
